import Foundation

enum LevelStory {
    static func mission(for levelID: Int) -> String {
        missions[levelID] ?? "Finish the pattern."
    }

    static func winLine(for levelID: Int) -> String {
        wins[levelID] ?? "Nice parking!"
    }

    private static let missions: [Int: String] = [
        1: "Park the race cars in color order.",
        2: "Help the Model T find its colors.",
        3: "Line up the bus pairs.",
        4: "Topolino takes three color turns.",
        5: "Keep the jeep AB rolling.",
        6: "Ambulance pairs need a home.",
        7: "Finish the pickup bounce.",
        8: "Wave the classic colors home.",
        9: "Warm colors climb the coupe ramp.",
        10: "Cool colors for the fire truck bay.",
        11: "Who rolls next in the street parade?",
        12: "Classic friends take turns.",
        13: "Twin trucks roll two by two.",
        14: "Keep the rescue dance going.",
        15: "Yard machines: loader, carrier…",
        16: "One taxi, then two buses.",
        17: "Two sports cars, then a hatch.",
        18: "Work convoy: pickup, dump, garbage.",
        19: "Four vehicles, then again.",
        20: "Ambulance wants its friends home.",
        21: "Hold the long AB rhythm.",
        22: "Three bus colors take turns.",
        23: "Finish the second jeep AB.",
        24: "Coral, then two mints, again.",
        25: "Two and two on the police bridge.",
        26: "Wagon ABC once more.",
        27: "Out on Classic Lane, then back.",
        28: "Mint and apricot keep the tanker going.",
        29: "Four festival colors in order.",
        30: "Model T quartet, finish the round.",
        31: "City and taxi walk the long street.",
        32: "Fire, police, ambulance, again.",
        33: "Box and tanker keep the yard rhythm.",
        34: "Model T, then two Topolinos.",
        35: "Two semis, two carriers.",
        36: "Loader, bus, kart, garage ABC.",
        37: "Out through the mirror, then home.",
        38: "Four vehicles fill the busy yard.",
        39: "Two sports, then a coupe.",
        40: "Dump, delivery, ambulance convoy.",
        41: "Three kart colors, park three.",
        42: "Bus, fire, Model T mega fleet.",
        43: "Mint and peri chorus, keep going.",
        44: "Rescue chorus all the way home.",
        45: "Two coral, two teal, bus pulse.",
        46: "Two semis, two tankers, work pulse.",
        47: "Four Topolino colors in a ribbon.",
        48: "Yard ribbon: bus, jeep, dump, tractor.",
        49: "Crown classics, finish the round.",
        50: "Crown finale, park the last four."
    ]

    private static let wins: [Int: String] = [
        1: "Race bay is lit!",
        2: "Model T found its spot.",
        3: "Bus pairs are parked.",
        4: "Topolino's turn is done.",
        5: "Jeep bay is humming.",
        6: "Ambulance is safe home.",
        7: "Pickup bounce complete.",
        8: "Classic wave is in.",
        9: "Warm bay is glowing.",
        10: "Cool bay is ready.",
        11: "Street parade rolls on.",
        12: "Classic friends are parked.",
        13: "Twin trucks tucked in.",
        14: "Rescue dance complete.",
        15: "Yard machines settled.",
        16: "City hop is done.",
        17: "Sport pair is home.",
        18: "Work convoy parked.",
        19: "Quartet bay is full.",
        20: "Ambulance bay shines.",
        21: "Long run parked clean.",
        22: "Bus trio is in.",
        23: "Jeep rhythm holds.",
        24: "Semi sandwich stacked.",
        25: "Police bridge complete.",
        26: "Wagon ABC is home.",
        27: "Mirror lane walks back.",
        28: "Tanker is repaired.",
        29: "Festival colors parked.",
        30: "Model T quartet done.",
        31: "Long street is clear.",
        32: "Rescue trio is home.",
        33: "Work rhythm holds.",
        34: "Classic sandwich parked.",
        35: "Pair convoy is in.",
        36: "Garage ABC complete.",
        37: "Mirror garage settled.",
        38: "Busy yard is calm.",
        39: "Sport trail is done.",
        40: "Broken convoy fixed.",
        41: "Mega kart bridge lit.",
        42: "Mega fleet is home.",
        43: "Pickup chorus sings.",
        44: "Rescue chorus complete.",
        45: "Bus pulse is steady.",
        46: "Work pulse is strong.",
        47: "Topolino ribbon shines.",
        48: "Yard ribbon is full.",
        49: "Crown classics parked.",
        50: "Every garage bay is full!"
    ]
}
